### ISSUE TITLE
Does this project have flow credentials?

### ISSUE THREAD

**Issue by jsolderitsch** [knolleary/a-test-node-red-project#1]
I am following along with the video:
[](https://www.youtube.com/watch?v=Bto2rz7bY3g)

I am tying to clone this repo to my local node-RED copy.

The clone seems to go correctly but the flows don't start with the message that there is an Invalid encryption key.

Don't know if this is a problem on my end? Do I need to be told what the credential decryption key is?

**Comment by knolleary** [comment]
This is a throw-away repo that I used to create the video - it wasn't intended to be cloned by others. Its encryption key is actually one I use elsewhere, so I'm not going to share it.

If you want an example project you can clone, which has encryption disabled, the cookbook flows project is here: https://github.com/node-red/cookbook-flows

**Comment by jsolderitsch** [comment]
Nick, Thanks for the quick reply.

I was beginning to think that the project used in the video was not meant for public use.

And there is a key there that is not release-able.

I will try this other one to make sure that I have things set up right.

Jim

On Feb 19, 2019, at 4:02 PM, knolleary <notifications@github.com<mailto:notifications@github.com>> wrote:


This is a throw-away repo that I used to create the video - it wasn't intended to be cloned by others. Its encryption key is actually one I use elsewhere, so I'm not going to share it.

If you want an example project you can clone, which has encryption disabled, the cookbook flows project is here: https://github.com/node-red/cookbook-flows<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnode-red%2Fcookbook-flows&data=02%7C01%7Cjames.j.solderitsch%40villanova.edu%7C8020f57922ae43f4d5ba08d696ad92f5%7C765a8de5cf9444f09cafae5bf8cfa366%7C0%7C0%7C636862069577141109&sdata=cq0TbOh75YSmoZiEm8rr8%2BnXTPuUxTyxbnEBVj6CIs4%3D&reserved=0>
